### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by stevescavo** [MadeInHaus/react-starter#1]
The README is basically empty, need to change that.

**Comment by cjthedizzy** [comment]
I will make a first pass at this after I've PR'ed feature-scoped-element-kit branch and its accepted. I would also like to add a unit test suite but I can come back and update again once thats in place

**Comment by ClayCooperLA** [comment]
@stevescavo let me know if there's anything you want me to elaborate on in the ReadMe update. I have additional markdown coming to the `screenshot` branch where I am tidying up the process a bit.
