### ISSUE TITLE
Add Thunk/Async Example

### ISSUE THREAD

**Issue by unruffledBeaver** [MadeInHaus/react-starter#21]
Add an example of an action and a thunk. Maybe call something like the GitHub API since its public and pull some of HAUS' profile info and display it in the Home or About Route

**Comment by rynocouse** [comment]
One option is to maintain a sample code branch. This would make it easier to remove all sample code by generating a .patch file against dev.

**Comment by stevescavo** [comment]
This is probably beyond the scope of this starter, so I'm closing.
