### ISSUE TITLE
Fix storybook config

### ISSUE THREAD

**Issue by stevescavo** [MadeInHaus/react-starter#36]

**Comment by stevescavo** [comment]
@unruffledBeaver [I've upgraded Storybook to 5.x](https://github.com/MadeInHaus/react-starter/commit/7eb0cf99978afb7afb8e0b646b223c191ca40eb9). I think we should either get it working again (obviously) or remove the package and related parts entirely.

**Comment by ClayCooperLA** [comment]
I have storybook working now.
