### ISSUE TITLE
Upgrade Packages and Approaches

### ISSUE THREAD

**Issue by chrisjcodes** [MadeInHaus/react-starter#39]
- [x] Upgrade packages to latest versions
- [x] Simplify organization of Redux files
- [ ] Swap out classes for hook implementations
- [ ] Add unit, e2e, and screenshot testing
- [ ] Convert `jsx` to `js`
- [ ] Bid adieu to "magic import" and switch to `index.js` entry points
- [ ] Simplify directory structure by promoting `src` to the root
- [x] Simplify the alias approach of just adding an `@/` alias for the root

**Comment by stevescavo** [comment]
Closing this issue so we can break these specific tasks and features out into discrete issues as needed.
