### ISSUE TITLE
Switch our private npm registry from Sinopia to Verdaccio

### ISSUE THREAD

**Issue by stevescavo** [MadeInHaus/react-starter#4]
Sinopia has been abandoned and we're running into npm/yarn dependency issues. I think it might be time to switch to [Verdaccio](https://github.com/verdaccio/verdaccio), an updated fork of the project.

**Comment by chromano** [comment]
Do we host private packages? how's the current sinopia configuration?

**Comment by stevescavo** [comment]
As a default, we've settled on pulling dependencies straight from npm.
