### ISSUE TITLE
Inline CSS strategy

### ISSUE THREAD

**Issue by rynocouse** [MadeInHaus/react-starter#7]
Come up with a strategy to inline critical CSS to prevent FOUC (flash of unstyled content)

**Comment by cjthedizzy** [comment]
@stevescavo assigned to you since you have something going for this already

**Comment by stevescavo** [comment]
@claus can you grab this task? I think we should lean on a webpack plugin or a similar approach for this: https://www.npmjs.com/package/webpack-plugin-critical
